server:
  port: 8090

spring:
  profile:
    active:
      - prod
  datasource:
    url: jdbc:mysql://localhost/db_ciclismo?useTimezone=true&serverTimezone=UTC
    username: root #alterar seu user e senha
    password: luzinete14
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update