server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ciclismocamelo@gmail.com
    password: luigunfrkvkubjeg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  profile:
    active:
      - prod

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JWT_SECRET:chaveBolada}

flyway:
  url: jdbc:mysql://${DB_HOST}:${DB_PORT}/
  schemas: ${DB_DATABASE}
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    config-url: /swagger-config.json



