server:
  port: 8080

spring:
  profile:
    active:
      - prod

  datasource:
    url: jdbc:mysql://localhost/db_ciclismo?useTimezone=true&serverTimezone=UTC
    username: root
    password: 200622pmr
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JWT_SECRET:chaveBolada}

flyway:
  url: jdbc:mysql://localhost:3306/
  schemas: db_ciclismo
  user: root
  password: 200622pmr

springdoc:
  swagger-ui:
    config-url: /swagger-config.json
