server:
  port: 8080

spring:
  profile:
    active:
      - prod
  datasource:
    url: jdbc:mysql://localhost/db_ciclismo?useTimezone=true&serverTimezone=UTC
    username: root #Seu user
    password: admin123 #Sua senha
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


api:
  security:
    token:
      secret: ${JWT_SECRET:chaveBolada}

  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: db_ciclismo
    user: root #Seu User
    password: admin123 #SUA SENHA