-- V1__Create_User_Table.sql
CREATE TABLE User (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(35) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    ROLE VARCHAR(20) NOT NULL
);


