-- V2__Create_Group_Table.sql
CREATE TABLE CyclistGroup (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(35) NOT NULL,
    PRIVACY BOOLEAN NOT NULL,
   
);