CREATE TABLE Profile (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    NICK_NAME VARCHAR(50),
    SEX VARCHAR(10) NOT NULL,
    CYCLING_CATEGORY VARCHAR(50),
    USER_TYPE VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(100),
    PROFILE_PICTURE BLOB
);