-- V3__Create_Profile_Table.sql
CREATE TABLE Profile(
    ID bigint PRIMARY KEY AUTO_INCREMENT,
    USER_ID bigint NOT NULL,
    FULLNAME VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(255),
    SEX VARCHAR(20) NOT NULL,
    CATEGORY VARCHAR(35) NOT NULL,
    LOCALITY VARCHAR(35) NOT NULL,
    PROFILEPICTURE BLOB,

    FOREIGN KEY (USER_ID) REFERENCES User(ID)

);

