name: Deploy Ciclismo Application

on:
    push:
        branches:
            - main
            - CriandoActionsDeploy

jobs:
    build:
        name: Build Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'
            - name: Build Project
              run: mvn clean install -DskipTests
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p '${{secrets.DOCKERHUB_PASSWORD}}'
            - name: Build Docker Image
              run: docker build -t ryanjorgeac/api-ciclismo .
            - name: Push Docker Image
              run: docker push ryanjorgeac/api-ciclismo
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Application Image from Docker Hub
        run: docker pull ryanjorgeac/api-ciclismo:latest
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name deploy-api-ciclismo ryanjorgeac/api-ciclismo